version: "3.8"
services:
  web-app:
    image: web-app
    container_name: web-app
    build:
      context: ./web-app
      dockerfile: Dockerfile
    environment:
      - VIRTUAL_HOST=cogitodev.org
      - LETSENCRYPT_HOST=cogitodev.org
      - VIRTUAL_PORT=3000
      - PORT=3000
    ports:
      - 3000:3000
    restart: always
    networks:
      - reverse-proxy

networks:
  reverse-proxy:
    external:
      name: reverse-proxy
